### ISSUE TITLE
Requesting for AutoPlay feature

### ISSUE THREAD

**Issue by MgMgPyaeSoneWin** [DZuz14/React-Image-Viewer#1]
# How it could implement autoplay slider

- adding a delay timer for 2 seconds and play next. How should I?

**Comment by DZuz14** [comment]
I can look into this for you. Sorry, I wish Github emailed me when this was first created, I had no idea you posted something. I will try to turn on notifications.

**Comment by MgMgPyaeSoneWin** [comment]
```
  componentDidMount() {
    this.interval = setInterval(() => this.nextSlide(), 3000)
  }

  componentWillUnmount() {
    clearInterval(this.interval)
  }

```
I just want to wonder if I want to play these sliders automatically, will it be the right way to make it?

**Comment by DZuz14** [comment]
You might want to read this [question](https://stackoverflow.com/questions/36299174/setinterval-in-a-react-app). You should be using your components state to store any type of information about your running processes. I am currently working on an example as well, and will push it live to the demo of this slider so you can see it working.

**Comment by DZuz14** [comment]
I have a very simple rendition working. I use the built in React method, "componentDidUpdate" to easily trigger my goToNextSlide function. Check it out if you are interested. [https://react-slider.herokuapp.com/](url)

**Comment by DZuz14** [comment]
You are on the right track. I did something similar to what you wanted to do with a setInterval function. You can check out the working example by clicking enable autoplay in the working demo here [https://react-slider.herokuapp.com/](url)

In the code, you can find the logic for this inside the "componentDidUpdate" method inside of the "Slider" component.
